### ISSUE TITLE
CSS doesn't appear to be showing up.

### ISSUE THREAD

**Issue by Kyle-Jackson** [Kyle-Jackson/dsn1674-project-1#1]
@thomasjbradley 

When I go to the link http://kyle-jackson.github.io/dsn1674-project-1/ it just has a white background with the basic font. It appears as if it isn't including the CSS file I created when I preview it even though the CSS is showing up when I just look at the code on Github. When I preview the file by dragging and dropping it into chrome it works fine and looks like how I want it to but for some reason when I preview it with the Github link that I submitted to doesn't.

My github account is:
https://github.com/Kyle-Jackson

**Comment by thomasjbradley** [comment]
Double check that all your files and folders follow our naming convention.

**Comment by Kyle-Jackson** [comment]
@thomasjbradley
I checked and all of my files follow the proper naming convention. When drag my file into the browser it looks fine but when I look at it on Github there is just the white background.
![screen shot 2015-02-09 at 10 27 05 am](https://cloud.githubusercontent.com/assets/10464623/6109132/b95afd7a-b046-11e4-9866-11018928596f.png)
This is what it looks like when I drag the file into my browser.

**Comment by thomasjbradley** [comment]
![screen shot 2015-02-09 at 10 57 04 am](https://cloud.githubusercontent.com/assets/105192/6109668/7683e6d4-b04a-11e4-910f-69d026c2dc4c.png)

**Comment by Kyle-Jackson** [comment]
@thomasjbradley 
I checked the css and everything looked normal, is it okay if it isn't showing up properly but the actual code itself looks fine?

**Comment by thomasjbradley** [comment]
> Is it okay if it isn't showing up properly but the actual code itself looks fine?

Nope, it's not okay.

---

That folder, on GitHub, has capital letters in it. Does it not have capital letters on your computer?

**Comment by Kyle-Jackson** [comment]
@thomasjbradley
Yes, the folder on my computer also has capital letters.

**Comment by Kyle-Jackson** [comment]
@thomasjbradley 
What do you recommend I do since all of the files seem to look okay but the css still doesn't seem to be working on the Github web page?
